# Autogenerated wrapper script for xtensor_io_jll for any
export xtensor_io

using Blosc_jll
using OpenImageIO_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("xtensor_io")
JLLWrappers.@declare_file_product(xtensor_io)
function __init__()
    JLLWrappers.@generate_init_header(Blosc_jll, OpenImageIO_jll, Zlib_jll)
    JLLWrappers.@init_file_product(
        xtensor_io,
        "include/xtensor-io/xtensor-io.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
